### ISSUE TITLE
How to help understand sentiments?

### ISSUE THREAD

**Issue by leegititssiyao** [LiquanChai/DS4D#2]
I found that it's a little bit tricky to tell the meanings of sentiments line chart, because both of humans and bots have opinions of "leave" and "remain". 
We cannot simply say the data above the x-axis means positive and below the x-axis means negative; opinions of "leave" can be expressed as positive or negative, "remain" as well.

Do you have any ideas about how to understand this line chart more sensibly? Or can we just use it to explain how excited they were? Or let's say how distinct their opinions were? Does it make sense?

**Comment by LiquanChai** [comment]
Rather than showing positive or negative towards leave and remain, the sentiment value itself can express the degree of sentiment. Maybe we can add this dimension to see the difference between bots and human.

**Comment by IvanLLL** [comment]
Right. The sentiment analysis of leave or remain is much more complicated in our case, which needs further natural language processing efforts. We can only focus on the sentiment degree of their tweets (no matter leave, remain or neutral) and see the difference between bots and human.
