### ISSUE TITLE
How to show the `Word-Treemap` better?

### ISSUE THREAD

**Issue by IvanLLL** [LiquanChai/DS4D#3]
Any idea to show the `word-treemap` better? from the perspective of colors, word filtering or anything else.

**Comment by LiquanChai** [comment]
I think we can use colours to differentiate opinions (hashtags).
hashtags that support "Leave" should different from those support "Remain" or "Neutral".

**Comment by leegititssiyao** [comment]
I think we can ignore neutral hashtags and only put those hashtags which can show users' opinions distinctly, so we could see the difference between humans and bots more clearly :)
